using UnityEngine;

public class ChickenNet : MonoBehaviour
{

    [Header("Taille du filet (zone de capture)")]
    public float captureRadius = 1.5f;

    void Update()
    {

        CheckCapture();
    }

    void CheckCapture()
    {
        // On cherche tous les poulets autour du filet
        Collider[] hits = Physics.OverlapSphere(transform.position, captureRadius);

        foreach (var hit in hits)
        {
            if (hit.CompareTag("Chicken"))
            {
                Destroy(hit.gameObject); // capture !
                Debug.Log("üêî Poulet captur√© !");
            }
        }
    }

#if UNITY_EDITOR
    // Dessine la zone de capture dans la sc√®ne
    void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, captureRadius);
    }
#endif
}